import Head from "next/head";
import Link from "next/link";
import React, { useState, useEffect } from "react";
import styles from "@/styles/Home.module.css";


interface Product {
  id: number;
  title: string;
}
const Products = () => {
  const [products, setProducts] = useState([]);

  useEffect(() => {
    fetch("https://dummyjson.com/products")
      .then((res) => res.json())
      .then(({ products }) => {
        setProducts(products);
      });
  }, []);

  return (
    <>
      <Head>
        <title>Products</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.nav}>
        <Link href={"/"}>Ir al inicio</Link>
      </nav>
      <main className={styles.main}>
        <h1>Products</h1>
        <ul>
          {products.map((p: Product) => (
            <li key={p.id}>
              <Link href={`/products/${p.id}`}>{p.title}</Link>
            </li>
          ))}
        </ul>
      </main>
    </>
  );
};

export default Products;
