import Head from "next/head";
import Link from "next/link";
import React, { useState, useEffect } from "react";
import styles from "@/styles/Home.module.css";


const Home = () => {
  return (
    <>
      <Head>
        <title>Clase 2 - Rutas dinámicas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}> 
              <Link href={`/products`} className={styles.button}>Ir a todos los Products</Link>
          
      </main>
    </>
  );
}

  

export default Home;
